server:
  port: 9095

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bbc_bookingservice
  application:
    name: booking-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/BlaBlaCar2025

  mvc:
    hiddenmethod:
      filter:
        enabled: true

blablacar:
  booking-service:
    version: 0.0.1

logging:
  level:
    org.springframework.security: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include: env
