server:
  port: 9095

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bbc_bookingservice
  application:
    name: booking-service

  mvc:
    hiddenmethod:
      filter:
        enabled: true

blablacar:
  trip-service:
    version: 0.0.1

logging:
  level:
    org.springframework.security: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        loggerLevel: FULL
