server:
  port: 9093

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bbc_notificationservice
  application:
    name: notification-service

  mvc:
    hiddenmethod:
      filter:
        enabled: true

blablacar:
  notification-service:
    version: 0.0.1

logging:
  level:
    org.springframework.security: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


feign:
  client:
    config:
      default:
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include: env
