server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbc_ratingservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/BlaBlaCar2025

  application:
    name: rating-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

blablacar:
  rating-service:
    version: 0.0.1

logging:
  level:
    org.springframework.security: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include: env