server:
  port: 9096

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bbc_telegramservice
  application:
    name: telegram-service

  mvc:
    hiddenmethod:
      filter:
        enabled: true

blablacar:
  telegram-service:
    version: 0.0.1

logging:
  level:
    org.springframework.security: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include: env
