server:
  port: 9094

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbc_discoveryservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: BlaBlaCar2025 Trip Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

blablacar:
  trip-service:
    version: 0.0.1

logging:
  level:
    org.springframework.security: TRACE