server:
  port: 9091

spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/bbc_userservice
     username: postgres
     password: postgres
     driver-class-name: org.postgresql.Driver
  cloud:
    stream:
      bindings:
        emailEventSentConsumer-in-0:
          destination: email-topic
          group: email-event-queue

  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

blablacar:
  user-service:
    version: 0.0.1

logging:
  level:
    org.springframework.security: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        loggerLevel: FULL

management:
  endpoints:
    web:
      exposure:
        include: env

resilience:
  circuitbreaker:
    instances:
      user-service:
#        properties


